[tool.poetry]
name = "birbia-station-bot"
version = "1.1.7"
description = "Birbia's Radio discord bot."
authors = ["SkinnyDevi <xthesmartdartx@gmail.com>"]
maintainers = ["SkinnyDevi <xthesmartdartx@gmail.com>"]
readme = "README.md"
packages = [{include = "birbia_station"}]
repository = "https://github.com/SkinnyDevi/birbia-station-bot"

[tool.poetry.dependencies]
python = "^3.8"
yt-dlp = "^2023.1.6"
async-timeout = "^3.0.1"
PyNaCl = "^1.4.0"
websockets = ">=6.0,<10.0"
aiohttp = ">=3.3.0,<3.9.0"
"discord.py" = "^2.0.1"
ffmpeg = "^1.4"
ffmpeg-python = "^0.2.0"
MarkupSafe = "2.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[tool.poetry.scripts]
bot = "birbia_station.main:start_bot"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
