[tool.poetry]
name = "birbia-station-bot"
version = "1.1.5"
description = "Birbia's Radio discord bot."
authors = ["SkinnyDevi <xthesmartdartx@gmail.com>"]
maintainers = ["SkinnyDevi <xthesmartdartx@gmail.com>"]
readme = "README.md"
packages = [{include = "birbia_dc_bot"}]
license = "Propietary"
repository = "https://github.com/SkinnyDevi/birbia-station-bot"

[tool.poetry.dependencies]
python = "^3.8"
youtube-dl = "^2021.12.17"
async-timeout = "^3.0.1"
PyNaCl = "^1.4.0"
websockets = ">=6.0,<7.0"
aiohttp = ">=3.3.0,<3.9.0"
"discord.py" = "^2.0.1"
ffmpeg = "^1.4"
ffmpeg-python = "^0.2.0"
MarkupSafe = "2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
